// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdW5DNGwtxL9HZjvkVyJbN1lX6PeiMxF0',
    appId: '1:154037024443:web:5c584612960cdfcefddb9e',
    messagingSenderId: '154037024443',
    projectId: 'equinox-db',
    authDomain: 'equinox-db.firebaseapp.com',
    storageBucket: 'equinox-db.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChtRqVdZpPsVQhyspetsYVywNxDFPW82E',
    appId: '1:154037024443:android:f230e92d8c49403bfddb9e',
    messagingSenderId: '154037024443',
    projectId: 'equinox-db',
    storageBucket: 'equinox-db.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZyvy4tUREuND_8-1mt7uIhc-djgH-TKc',
    appId: '1:154037024443:ios:a6038c51163848b1fddb9e',
    messagingSenderId: '154037024443',
    projectId: 'equinox-db',
    storageBucket: 'equinox-db.appspot.com',
    iosClientId: '154037024443-5d6dupql72pu00767el0k8qut9ioie3m.apps.googleusercontent.com',
    iosBundleId: 'com.example.tempStore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBZyvy4tUREuND_8-1mt7uIhc-djgH-TKc',
    appId: '1:154037024443:ios:a6038c51163848b1fddb9e',
    messagingSenderId: '154037024443',
    projectId: 'equinox-db',
    storageBucket: 'equinox-db.appspot.com',
    iosClientId: '154037024443-5d6dupql72pu00767el0k8qut9ioie3m.apps.googleusercontent.com',
    iosBundleId: 'com.example.tempStore',
  );
}
